import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Roboto = localFont({
  src: [
    { path: "../fonts/Roboto.ttf", weight: "400", style: "normal" },
    { path: "../fonts/Roboto.ttf", weight: "700", style: "normal" },
    { path: "../fonts/Roboto.ttf", weight: "300", style: "normal" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Roboto.className}`}>{children}</body>
    </html>
  );
}
